config/routes.rb
Rails.application.routes.draw do
  # For testing JS
  mount MagicLamp::Genie, at: "/magic_lamp" if defined?(MagicLamp)

  root 'pages#splash'

  get 'viewer' => 'pages#viewer', as: :viewer

  get 'about' => 'pages#about', as: :about # gives you about_path
  get 'contact' => 'pages#contact', as: :contact # gives you contact_path
  get 'citation' => 'pages#citation', as: :citation # gives you citation_path


  get 'biom' => 'pages#biom', as: :biom

  get 'large' => 'pages#canvas_viewer', as: :large
  get 'cluster' => 'pages#tree_cluster', as: :tree_cluster

  get 'pd' => 'pages#pd', as: :pd

  get 'classify' => 'pages#classify', as: :classify
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

  def contact
  end

  def error
  end

  def citation
  end

  def splash
  end

  def viewer
  end

  def canvas_viewer
  end

  def tree_cluster
  end

  def pd
  end

  def classify
  end

  def biom
    @color_brewer_colors = %w(Viridis Spectral CubeHelixDefault CubeHelixSaturated OrRd PuBu BuPu Oranges BuGn YlOrBr YlGn Reds RdPu Greens YlGnBu Purples GnBu Greys YlOrRd PuRd Blues PuBuGn RdYlGn RdBu PiYG PRGn RdYlBu BrBG RdGy PuOr Set2 Accent Set1 Set3 Dark2 Paired Pastel2 Pastel1)

    @color_brewer_colors_printable_names = %w(Viridis Spectral CubeHelix-Default CubeHelix-Saturated Orange-Red Purple-Blue Blue-Purple Oranges Blue-Green Yellow-Orange-Brown Yellow-Green Reds Red-Purple Greens Yellow-Green-Blue Purples Green-Blue Greys Yellow-Orange-Red Purple-Red Blues Purple-Blue-Green Red-Yellow-Green Red-Blue Pi-YG PR-Green Red-Yellow-Blue Brown-BG Red-Gy Purple-Orange Set2 Accent Set1 Set3 Dark2 Paired Pastel2 Pastel1)

    @palette_options = Hash[@color_brewer_colors.zip(@color_brewer_colors_printable_names)]

    @palette_interpolation_vals = {
        "palette-interpolation-mode-lab"        => { name: "Lab", val: "lab" },
        "palette-interpolation-mode-lab-bezier" => { name: "Bezier Lab", val: "lab-bezier" },
        "palette-interpolation-mode-rgb"        => { name: "Red-green-blue", val: "rgb" },
        "palette-interpolation-mode-lrgb"       => { name: "Linear red-green-blue", val: "lrgb" },
        "palette-interpolation-mode-hsl"        => { name: "Hue-saturation-lightness", val: "hsl" },
        "palette-interpolation-mode-lch"        => { name: "Hue-chroma-lightness", val: "lch" },
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  #
  # Eg., Iroki | About
  #
  # @param page_title [String] The title of the page
  #
  # @return [String] The nav bar title of the page
  def full_title page_title
    base_title = "Iroki"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_biom_form.html.slim
.row#everything

  ul#example-tabs.tabs data-tabs=""
    li.tabs-title.is-active
      a#upload-tab-button aria-selected="true" href="#upload-panel" Upload
    li.tabs-title
      a#options-tab-button-thick-right-border href="#options-panel" Options
    /li.tabs-title
    /  a#save-tab-button href="#save-panel" Save

  #form-div.tabs-content data-tabs-content="example-tabs"
    #upload-panel.tabs-panel.is-active
      = render "layouts/biom_upload_panel"
    #options-panel.tabs-panel
      = render "layouts/biom_options_panel"
    /#save-panel.tabs-panel
    /  = render "layouts/biom_palette_options"

app/views/layouts/_biom_geometry_options.html.slim
#geometry-options-div
  .row
    ul id="biom-options-accordion" class="accordion" data-accordion="" data-allow-all-closed="true"

      li class="accordion-item is-active" data-accordion-item=""
        a href="#" class="accordion-title" Data options
        .accordion-content data-tab-content=""
          = render "layouts/biom/data_options"

      li class="accordion-item" data-accordion-item=""
        a href="#" class="accordion-title" Color space options
        .accordion-content data-tab-content=""
          = render "layouts/biom/color_space_options"

      li class="accordion-item" data-accordion-item=""
        a href="#" class="accordion-title" Hue options
        .accordion-content data-tab-content=""
          = render "layouts/biom/hue_options"

      li class="accordion-item" data-accordion-item=""
        a href="#" class="accordion-title" Chroma (saturation) options
        .accordion-content data-tab-content=""
          = render "layouts/biom/chroma_options"

      li class="accordion-item" data-accordion-item=""
        a href="#" class="accordion-title" Lightness options
        .accordion-content data-tab-content=""
          = render "layouts/biom/lightness_options"

app/views/layouts/_biom_options_panel.html.slim
#options-div
  = render "layouts/biom_geometry_options"
  = render "layouts/biom_palette_options"

app/views/layouts/_biom_palette_options.html.slim
#palette-options-div
  .row
    .small-12.columns
      h3 Palette preview
      #palette-preview-container
        svg#palette-preview width=800 height=100

  .row
    ul id="biom-palette-options-accordion" class="accordion" data-accordion="" data-allow-all-closed="true"
      li class="accordion-item is-active" data-accordion-item=""
        a href="#" class="accordion-title" Direct palette options
        .accordion-content data-tab-content=""
          = render "layouts/biom/palette_options"

app/views/layouts/_biom_upload_panel.html.slim
hr.row

.row
  h4 Upload biom file
  form id="biom-file-upload-form"
    .row
      .small-12.medium-6.columns
        label for="uploader" Biom tsv file
        input id="uploader" type="file" name="biom"
      .small-12.medium-6.columns
        label for="download-legend" Create a legend?
        input id="download-legend" type="checkbox" checked=""
    .row
      .small-12.medium-6.columns
        label for="biom-conversion-style" Biom conversion style
        select id="biom-conversion-style"
          option id="biom-conversion-style-palette" value="biom-conversion-style-palette" selected="" Palette style
          option id="biom-conversion-style-geometry" value="biom-conversion-style-geometry" Geometry style
      .small-12.medium-6.columns
        label for="scale-matrix" Scale matrix for projection?
        input id="scale-matrix" type="checkbox"
    .row
      .small-12.medium-4.columns
        label for="submit-button" Submit file
        input id="submit-button" type="button" value="Submit!" disabled=""
      .small-12.medium-4.columns
        label for="reset-button" Reset form
        input id="reset-button" type="button" value="Reset!" disabled=""
      .small-12.medium-4.columns
        label for="save-button" Save result
        input id="save-button" type="button" value="Save!" disabled=""
hr.row

app/views/layouts/_canvas_viewer_upload_panel.html.slim
hr.row

.row
  h4 Upload tree
  form id="canvas-tree-upload-form"
    .small-12.columns
      label for="file-uploader" Newick tree
      input id="file-uploader" type="file"

hr.row

.row
  h4 Upload mapping file
  form id="canvas-mapping-upload-form"
    .row
      .small-12.columns
        label for="mapping-file-uploader" Mapping file
        input id="mapping-file-uploader" type="file"
    .row
      .small-12.columns
        label for="matching-type" Mapping file label matching
        select id="matching-type"
          option id="exact" value="exact" selected="" Exact
          option id="partial" value="partial" Partial (substring matching)

hr.row

.row
  h4 Submit
  .small-6.columns
    label for="submit" Submit your files
    input id="submit" type="button" value="Submit!" disabled=""
  .small-6.columns
    label for="reset" Reset the viewer
    input id="reset" type="button" value="Reset!"

hr.row

app/views/layouts/_check_download.html.slim
.row
  = form_tag({controller: "pages", action: "jobs"}, remote: false) do
    .row
      = label_tag :job_id
      = text_area_tag :job_id, @job_id
    .row
      = label_tag :dj_row_id
      = text_area_tag :dj_row_id, @dj_row_id
    .row
      = submit_tag("Check for job",
              class: "expanded button secondary",
              id: "check_for_job")

app/views/layouts/_docs_nav_bar.html.slim
.row
  ul.sand-color.vertical.dropdown.menu data-dropdown-menu="" style="max-width: 250px;"
    li = link_to 'Newick trees', docs_newick_path
    li
      = link_to 'Mapping files', docs_mapping_files_path
      ul.menu.sand-color
        li
          = link_to 'Palettes', docs_palettes_path
          ul.menu.sand-color
            / These are my favs
            li = link_to "Paul Tol Muted (color blind friendly)", "/palettes/palette_paul_tol_muted.pdf", id: "Paul Tol Muted"
            li = link_to "Kelly", "/palettes/palette_kelly.pdf", id: "Kelly"
            li = link_to "Paul Tol Bright (color blind friendly)", "/palettes/palette_paul_tol_bright.pdf", id: "Paul Tol Bright"
            / These are cool
            li = link_to "Color Brewer Accent", "/palettes/palette_brewer_accent.pdf", id: "Color Brewer Accent"
            li = link_to "Color Brewer Dark 2", "/palettes/palette_brewer_dark2.pdf", id: "Color Brewer Dark 2"
            li = link_to "Color Brewer Paired", "/palettes/palette_brewer_paired.pdf", id: "Color Brewer Paired"
            li = link_to "Color Brewer Set 1", "/palettes/palette_brewer_set1.pdf", id: "Color Brewer Set 1"
            li = link_to "Color Brewer Set 2", "/palettes/palette_brewer_set2.pdf", id: "Color Brewer Set 2"
            li = link_to "Paul Tol High Contrast (color blind friendly)", "/palettes/palette_paul_tol_high_contrast.pdf", id: "Paul Tol High Contrast"
            li = link_to "Paul Tol Vibrant (color blind friendly)", "/palettes/palette_paul_tol_vibrant.pdf", id: "Paul Tol Vibrant"
        li
          = link_to 'Styling options', docs_styling_opts_path
          ul.menu.sand-color
            li = link_to 'Branch styling', docs_branch_styling_path
        li
          = link_to 'Mapping file priority', docs_mapping_file_priority_path

app/views/layouts/_docs_nav_bar_title.html.slim
.row
  h1 = link_to 'Iroki Docs', docs_path

app/views/layouts/_options_panel.html.slim
#options-div
  .row
    ul id="options-accordion" class="accordion" data-accordion="" data-allow-all-closed="true"
      li class="accordion-item is-active" data-accordion-item=""
        a href="#" class="accordion-title" Tree format options
        .accordion-content data-tab-content=""
          .row
            .small-12.medium-12.large-6.columns
              label for="tree-shape" Layout shape
              select id="tree-shape"
                option id="rectangular-tree" value="rectangular-tree" Rectangular
                option id="circular-tree" value="circular-tree" Circular
                option id="radial-tree" value="radial-tree" Radial
            .small-12.medium-12.large-6.columns
              label for="tree-branch-style" Branch style?
              select id="tree-branch-style"
                option id="normalogram" value="normalogram" True length
                option id="cladogram" value="cladogram" Cladogram
          .row
            .small-12.columns
              label for="tree-sort" Sort?
              select id="tree-sort"
                option id="descending" value="descending" Sort
                option id="ascending" value="ascending" Reverse sort
                option id="not-sorted" value="not-sorted" Not sorted
          .row
            .small-12.columns
              label for="tree-rotation" Tree rotation
              input id="tree-rotation" class="slider width-100" type="range" min="0" max="270" step="270"
          .row
            .small-12.columns
              label for="biological-root" Tree root is biologically meaningful?
              input id="biological-root" type="checkbox" name="biological-root"

      li class="accordion-item" data-accordion-item=""
        a href="#" class="accordion-title" Tree size options
        .accordion-content data-tab-content=""
          .row
            .small-12.medium-12.large-6.columns
              label id="width-label" for="width" Horizontal
              input id="width" type="text"
            .small-12.medium-12.large-6.columns
              label id="height-label" for="height" Vertical
              input id="height" type="text"
          .row
            .small-12.columns
              label id="padding-label" for="padding" Padding
              input id="padding" class="slider width-100" type="range" min="0.0" max="0.75" step="0.05"

      li class="accordion-item" data-accordion-item=""
        a href="#" class="accordion-title" Scale bar options
        .accordion-content data-tab-content=""
          .row
            .small-12.medium-12.large-6.columns
              label for="show-scale-bar" Show scale bar?
              input id="show-scale-bar" type="checkbox"
            .small-12.medium-12.large-6.columns
              label for="scale-bar-offset-weight" Offset
              input id="scale-bar-offset-weight" class="slider width-100" type="range" min="1" max="2.5" step="0.1"
          .row
            .small-12.medium-12.large-6.columns
              label for="scale-bar-auto-size" Auto size
              input id="scale-bar-auto-size" type="checkbox"
            .small-12.medium-12.large-6.columns
              label for="scale-bar-length" Length
              input id="scale-bar-length"
      /input id="scale-bar-length-weight" class="slider width-100" type="range" min="0.25" max="2" value="1" step="0.25"

      li class="accordion-item" data-accordion-item=""
        a href="#" class="accordion-title" Label options
        .accordion-content data-tab-content=""
          .row
            .small-12.medium-12.large-6.columns
              label for="show-inner-labels" Show inner (bootstrap) labels?
              input id="show-inner-labels" type="checkbox" name="label-show"
            .small-12.medium-12.large-6.columns
              label for="inner-label-size" Inner label size
              input id="inner-label-size" type="range" min="1" max="48" class="slider width-100"

          .row
            .small-12.medium-12.large-6.columns
              span data-tooltip="" aria-haspopup="true" class="has-tip tip-top" title="Will not overide label colors in the mapping file."
                label for="inner-label-color" Inner label color
                input id="inner-label-color" type="color" value="#000000"
            .small-12.medium-12.large-6.columns
              label for="inner-label-font" Inner label font
              select id="inner-label-font"
                option id="inner-label-font-helvetica" value="Helvetica" Helvetica
                option id="inner-label-font-geneva" value="Geneva" Geneva
                option id="inner-label-font-tahoma" value="Tahoma" Tahoma
                option id="inner-label-font-verdana" value="Verdana" Verdana
                option id="inner-label-font-times" value="Times" Times
                option id="inner-label-font-georgia" value="Georgia" Georgia
                option id="inner-label-font-palatino" value="Palatino" Palatino
                option id="inner-label-font-courier" value="Courier" Courier
                option id="inner-label-font-monaco" value="Monaco" Monaco
          hr.row

          .row
            .small-12.medium-12.large-6.columns
              label for="show-leaf-labels" Show leaf labels?
              input id="show-leaf-labels" type="checkbox" name="label-show"
            .small-12.medium-12.large-6.columns
              label for="leaf-label-size" Leaf label size
              input id="leaf-label-size" type="range" min="1" max="48" class="slider width-100"
          .row
            .small-12.columns
              label for="leaf-label-padding" Leaf label padding
              input id="leaf-label-padding" type="text"

          .row
            .small-12.columns
              label for="align-tip-labels" Align tip decorations?
              input id="align-tip-labels" type="checkbox"
          .row
            .small-12.medium-12.large-6.columns
              span data-tooltip="" aria-haspopup="true" class="has-tip tip-top" title="Will not overide label colors in the mapping file."
                label for="leaf-label-color" Leaf label color
                input id="leaf-label-color" type="color"
            .small-12.medium-12.large-6.columns
              label for="leaf-label-font" Leaf label font
              select id="leaf-label-font"
                option id="leaf-label-font-helvetica" value="Helvetica" Helvetica
                option id="leaf-label-font-geneva" value="Geneva" Geneva
                option id="leaf-label-font-tahoma" value="Tahoma" Tahoma
                option id="leaf-label-font-verdana" value="Verdana" Verdana
                option id="leaf-label-font-times" value="Times" Times
                option id="leaf-label-font-georgia" value="Georgia" Georgia
                option id="leaf-label-font-palatino" value="Palatino" Palatino
                option id="leaf-label-font-courier" value="Courier" Courier
                option id="leaf-label-font-monaco" value="Monaco" Monaco


      li class="accordion-item" data-accordion-item=""
        a href="#" class="accordion-title" Dot options
        .accordion-content data-tab-content=""
          h4 Inner dots
          .row
            .small-12.columns
              label for="show-inner-dots" Show inner dots?
              select id="show-inner-dots"
                option id="show-inner-dots-none" value="show-inner-dots-none" None
                option id="show-inner-dots-normal" value="show-inner-dots-normal" Normal
                option id="show-inner-dots-bootstrap" value="show-inner-dots-bootstrap" Bootstrap support

          / Get vals for bootstrap support cutoff values.
          .row
            .small-12.medium-12.large-6.columns
              label for="bootstrap-cutoff-unfilled-dot" Bootstrap open dot cutoff
              input id="bootstrap-cutoff-unfilled-dot" type="text"
            .small-12.medium-12.large-6.columns
              label for="bootstrap-cutoff-filled-dot" Bootstrap filled dot cutoff
              input id="bootstrap-cutoff-filled-dot" type="text"
          .row
            .small-12.medium-12.large-6.columns
              label for="inner-dot-color" Inner dot color
              input id="inner-dot-color" type="color"
            .small-12.medium-12.large-6.columns
              label for="inner-dot-size" Inner dot size
              input id="inner-dot-size" type="range" min="2" max="8" class="slider width-100"

          h4 Leaf dots
          .row
            .small-12.medium-12.large-6.columns
              label for="show-leaf-dots" Show leaf dots?
              input id="show-leaf-dots" type="checkbox"
            .small-12.medium-12.large-6.columns
              label for="align-leaf-dots" Align tip decorations?
              input id="align-leaf-dots" type="checkbox"
          .row
            .small-12.medium-12.large-6.columns
              label for="leaf-dot-color" Leaf dot color
              input id="leaf-dot-color" type="color" value="#000000"
            .small-12.medium-12.large-6.columns
              label for="leaf-dot-size" Leaf dot size
              input id="leaf-dot-size" type="range" min="2" max="8" class="slider width-100"

      li class="accordion-item" data-accordion-item=""
        a href="#" class="accordion-title" Bar options
        .accordion-content data-tab-content=""
          .row
            .small-12.medium-12.large-6.columns
              label for="show-bars" Show bars?
              input id="show-bars" type="checkbox"
            .small-12.medium-12.large-6.columns
              label for="show-bar-start-axis" Show bars axis?
              input id="show-bar-start-axis" type="checkbox"
          .row
            .small-12.columns
              label for="align-bars" Align tip decorations?
              input id="align-bars" type="checkbox"
          .row
            .small-12.columns
              label for="bar-color" Default bar & axis color
              input id="bar-color" type="color" value="#bababa"
          .row
            .small-12.columns
              label for="bar-padding" Bar padding
              input id="bar-padding" type="text"
          .row
            .small-12.medium-12.large-6.columns
              label for="bar-height" Max bar height
              input id="bar-height" type="range" min="1" max="200" class="slider width-100"
            .small-12.medium-12.large-6.columns
              label for="bar-width" Bar width
              input id="bar-width" type="range" min="1" max="50" class="slider width-100"

      li class="accordion-item" data-accordion-item=""
        a href="#" class="accordion-title" Arc options
        .accordion-content data-tab-content=""
          .row
            .small-12.columns
              label for="arcs-show" Show arcs?
              input id="arcs-show" type="checkbox"
          .row
            .small-12.columns
              label for="arcs-padding" Arc padding
              input id="arcs-padding" type="text"
          .row
            .small-12.medium-12.large-6.columns
              label for="arcs-height" Arc height
              input id="arcs-height" type="range" min="1" max="200" class="slider width-100"
            .small-12.medium-12.large-6.columns
              label for="arcs-cap-radius" Arc cap radius
              input id="arcs-cap-radius" type="range" min="1" max="10" class="slider width-100"

      li class="accordion-item" data-accordion-item=""
        a href="#" class="accordion-title" Branch options
        .accordion-content data-tab-content=""
          .row
            .small-12.medium-12.large-6.columns
              label for="branch-color" Color
              input id="branch-color" type="color"
            .small-12.medium-12.large-6.columns
              label for="branch-width" Width
              input id="branch-width" type="range" min="1" max="10" class="slider width-100"

      li class="accordion-item" data-accordion-item=""
        a href="#" class="accordion-title" Viewer options
        .accordion-content data-tab-content=""
          .row
            .small-12.columns
              label for="viewer-size-fixed" Fixed viewer width?
              input id="viewer-size-fixed" type="checkbox"

app/views/layouts/_save_panel.html.slim
hr.row

.row
  h4 Save tree
  h5 SVG
  .small-12.columns
    label for="save-svg" Save?
    input id="save-svg" type="button" value="Save as SVG" disabled=""

hr.row

.row
  h5 PNG
  / .row
  /   .small-12.columns
  /     label for="current-size" Image size <em>(in pixels; as seen in the viewer)</em>
  /     input type="text" id="current-size" disabled=""
  .row
    h6 Output options
  .row
    .small-12.columns
      label for="save-scaling-factor" <b>Scale</b> <em>(percentage; 100% means no scaling; increase or decrease to change output image size!)</em>
      input id="save-scaling-factor" type="text" name="save-scaling-factor" value="100"
    .small-12.columns
      label for="desired-ppi" <b>Image resolution?</b> <em>(72 - 4000 PPI)</em>
      input id="desired-ppi" type="number" name="desired-ppi" min="72" max="4000" value="72"

  .row
    h6 Output image info
  .row
    .small-12.columns
      label for="size-at-desired-ppi-pixels" Output image size <em>(in pixels)</em>
      input type="text" id="size-at-desired-ppi-pixels" disabled=""
    .small-12.columns
      label for="size-at-desired-ppi-inches" Output image size at selected resolution <em>(in inches)</em>
      input type="text" id="size-at-desired-ppi-inches" disabled=""

  .row
    .small-12.columns
      label id="label-for-save-png" for="save-png" Save? <em>(large trees may take a while!)</em>
      input id="save-png" type="button" value="Save as PNG" disabled=""

hr.row

app/views/layouts/_upload_form_simple.html.slim
.row
  .row
    ul.tabs#option-tabs data-tabs=""
      .small-5.columns.center-it
        li.tabs-title.is-active.center-it
          a href="" Upload
.row.tabs-content data-tabs-content="option-tabs"
  .row.tabs-panel.is-active
    hr.row
    = form_tag({controller: "pages", action: "submit"}, multipart: true) do
      .row
        h4 Files
        .row
          = label_tag :newick_file
          = file_field_tag :newick_file
        .row
          = label_tag :color_map
          = file_field_tag :color_map
        .row
          = label_tag :name_map
          = file_field_tag :name_map
        .row
          = label_tag :biom_file
          = file_field_tag :biom_file
      hr.row
      .row
        h4 Options
        .row
          .medium-4.columns
            = check_box_tag(:color_branches)
            = label_tag(:color_branches, "Color branches?")
          .medium-4.columns
            = check_box_tag(:color_labels)
            = label_tag(:color_labels, "Color labels?")
          .medium-4.columns
            = check_box_tag(:exact)
            = label_tag(:exact, "Exact matching?")
        .row
          .row
            = label_tag(:auto_color, "Auto color palettes")
          .row
            = select_tag(:auto_color, options_for_select([["Kelly", "kelly"]]))
      hr.row
      .row
        h4 Gradient type
        .row
          .medium-6.columns
            = radio_button_tag(:single_color, true)
            = label_tag(:single_color_true, "Single color")
          .medium-6.columns
            = radio_button_tag(:single_color, false)
            = label_tag(:single_color_false, "Two color")
      .row
        h4 Gradient luminosity
        .row
          .medium-6.columns
            = label_tag(:min_lumin, "Minimum luminosity")
            = select_tag(:min_lumin, options_for_select((1..100).zip(1..100), 35))
          .medium-6.columns
            = label_tag(:max_lumin, "Maximum luminosity")
            = select_tag(:max_lumin, options_for_select((1..100).zip(1..100), 70))
      hr.row
      .row
        = submit_tag("Submit",
                class: "expanded button secondary please-wait",
                onmouseclick: 'this.disabled = true;')

app/views/layouts/_viewer_form.html.slim
.row#everything

  ul#example-tabs.tabs data-tabs=""
      li.tabs-title.is-active
        a#upload-tab-button aria-selected="true" href="#upload-panel" Upload
      li.tabs-title
        a#options-tab-button href="#options-panel" Options
      li.tabs-title
        a#save-tab-button href="#save-panel" Save

  #form-div.tabs-content data-tabs-content="example-tabs"
    #upload-panel.tabs-panel.is-active
      = render "layouts/upload_panel"
    #options-panel.tabs-panel
      = render "layouts/options_panel"
    #save-panel.tabs-panel
      = render "layouts/save_panel"

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? full_title(yield(:title)) : "Iroki"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => false
    = csrf_meta_tag

  body
    == render 'layouts/nav_bar'
    == yield
    == debug(params) if Rails.env.development?

app/views/layouts/biom/_color_space_options.html.slim
.row
  .small-12.columns
    label for="color-space" Color space
    select id="color-space"
      option id="color-space-hcl" value="color-space-hcl" selected="" Hue Chroma Lightness
      option id="color-space-hsl" value="color-space-hsl" Hue Saturation Lightness

app/views/layouts/biom/_hue_options.html.slim
.row
  .small-12.columns
    label style="font-weight: bold;" id="hue-angle-offset-label" for="hue-angle-offset" Approximate starting hue
    input id="hue-angle-offset" type="range" min="0" max="359" value="0" step="0"

app/views/pages/citation.html.slim
- provide :title, 'Citation'

.row
  h1 Citation
.row
  = render "layouts/citation"
.row
  h2 Thank you!!
.row
  = image_tag "/please_cite.jpg", id: "please-cite"

app/views/pages/viewer.html.slim
- provide :title, 'Online phylogenetic tree viewer with automatic customization using metadata or biom files'

.row.expanded.thick-border
  .small-12.medium-6.large-4.columns#outer-container
    .row.upload-form
      = render "layouts/viewer_form"

    .row
      h1 Iroki tree viewer
    .row
      p Hi! I'm the Iroki tree viewer!
      / p Hi! I'm the Iroki tree viewer for normal sized trees!
      / p If you have a really big tree (up to one million leaves!), you should try the #{link_to "large tree viewer", large_path}.

    .row
      h3 About
      p Iroki is a super snazzy online tree viewer (phylogenetic or other kinds too!) with automatic customization using metadata or biom files.

      p You can visualize your newick trees as well as project count data into colors that you can use to style the tree!
      /p If you have a biom file with abundance info that you want to convert to a color map, click #{link_to "here", biom_path}.

      p If you need to pick colors for your tree, we suggest using #{link_to 'one of the lovely palettes included in Iroki', "/wiki#Color%20Palettes"}!!
    .row
      h3 Citation
      = render "layouts/citation"
    .row
      h3 Documentation
      p To see usage examples and learn about how to customize your trees, check out the #{link_to "documentation", "/wiki"}.
    .row
      h3 Getting help
      p If you have any problems running Iroki, please #{mail_to "admin@iroki.net", "send us an email", cc: "IrokiHelp@gmail.com", subject: "Iroki help", target: "blank"}!

  .small-12.medium-6.large-8.columns
    #status-msg-container
      h3#status-msg Please report any bugs on the contact page.
    .row#tree-div

javascript:
  upload_button("submit", "uploader", utils__load_dataset);